config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :missions
  resources :packets
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :packet
  attr_accessible :map, :name, :objective, :specialRules, :tacticalTips, :victory, :packet_id
end

app/models/packet.rb
class Packet < ActiveRecord::Base
  attr_accessible :title
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

	def index
        @packets = Packet.all
		@missions = Mission.where("'created_at' > '2013'")
	end

	def show
		@mission = Mission.find(params[:id])
	end

	def new
        authorize! :index, @user, :message => 'Not authorized to create new mission.'		
		@mission = Mission.new
	end
	
	def create
      authorize! :index, @user, :message => 'Not authorized to create new missions.'		
	  @mission = Mission.new(mission_params)
	  
		if @mission.save
			redirect_to @mission
		else
			render 'new'
		end
	end
	
	def edit
      authorize! :index, @user, :message => 'Not authorized to edit missions.'		
	  @mission = Mission.find(params[:id])
	end

	def update
        authorize! :index, @user, :message => 'Not authorized to update missions an administrator.'		
		@mission = Mission.find(params[:id])
	
        if @mission.update_attributes(params[:mission].permit(:packet_id, :name, :victory, :specialRules, :tacticalTips, :map, :objective))
            redirect_to @mission
        else
			render 'edit'
	    end
	end		

	def destroy
      authorize! :index, @user, :message => 'Not authorized to destroy missions.'		
	  @mission = Mission.find(params[:id])
	  @mission.destroy
 
	  redirect_to mission_path
	end

private
  def mission_params
    params.require(:mission).permit(:packet, :name, :victory, :specialRules, :tacticalTips, :map, :objective)
  end
end

app/controllers/packets_controller.rb
class PacketsController < ApplicationController
	def index
        @packets = Packet.all
	end
	def show
        @packet = Packet.find(params[:id])
		@missions = Mission.where("'created_at' > '2013' AND packet_id = ?", params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
Mission Generator
<% end %>

<% content_for :head do %>
<script type="text/javascript">
	function PrintMission(MissionNumber)
	{
		var MissionList = LoadMissionArray()

		document.getElementById("MissionName").innerHTML=MissionList[MissionNumber][0]+" ("+MissionList[MissionNumber][6]+")"; 
		document.getElementById("MissionVictoryConditions").innerHTML=MissionList[MissionNumber][1]; 
		document.getElementById("MissionSpecialRules").innerHTML=MissionList[MissionNumber][2]; 
		document.getElementById("MissionTacticalTips").innerHTML=MissionList[MissionNumber][3]; 
		document.getElementById("MissionMap").innerHTML=MissionList[MissionNumber][4]; 
		document.getElementById("MisionObjective").innerHTML=MissionList[MissionNumber][5]; 
	}

	function LoadMissionArray()
	{
		var i = 1

		var ImageSource = "http://sr20x.com/static/img/"

		var MissionList = new Array()

		MissionList.push("Select Mission");
       
		<% Mission.all.each_with_index do |mission, index| %>
			MissionList.push(new Array());
			MissionList[i].push("<%= mission.name %>");
			MissionList[i].push("<%= mission.victory.html_safe %>");
			MissionList[i].push("<%= mission.specialRules.html_safe  %>");
			MissionList[i].push("<%= mission.tacticalTips.html_safe %>");
			MissionList[i].push('<img src="'+ImageSource+'<%= mission.map %>"></img>');
			MissionList[i].push('<img src="'+ImageSource+'<%= mission.objective %>"></img>');
			MissionList[i].push("<%= Packet.find(mission.packet_id).title %>");

			i++
		<% end %>
	
		return MissionList
	}	
	
	function RandomMission()
	{
		var MissionNumber = Math.floor(Math.random()*12);

    if (MissionNumber == 0 || MissionNumber > 12)
    {
        RandomMission()
    }

		PrintMission(MissionNumber);
	}
	function SelectMission()
	{
		var SelectedMission = document.getElementById("missionList").value;

		PrintMission(SelectedMission);	
	}

	function ToggelSelect()
	{
		document.getElementById("GenerateButtonRow").className = "span8 hidden"
    document.getElementById("SelectListRow").className = "span8"
	}
	function ToggelGenerate()
	{
		document.getElementById("GenerateButtonRow").className = "span8"
    document.getElementById("SelectListRow").className = "span8 hidden"
	}
</script>
<% end %>
<div class="row">
<div class="span12">
<h3>Steamroller Mission Generator</h3>
	<div class="row">
		<div class="span1 offset8 hidden">
			<img onLoad="RandomMission()" src="http://sr20x.com/static/img/Steamroller.png"></img> 
		</div>
		<div class="span8" id="GenerateButtonRow">
			<button class="btn" id="GenerateMission" onClick="RandomMission()">Random Mission</button> <a id="ToggleSelect" onClick="ToggelSelect()" >Select Mission</a>
		</div>	
		<div class="span8 hidden" id="SelectListRow">	
			<select id="missionList" onChange="SelectMission()">
				<option value="">Select Mission</option>
				<option value="1">Destruction</option>
				<option value="2">Supply and Demand</option>
				<option value="3">Balance of Power</option>
				<option value="4">Process of Elimination</option>
				<option value="5">Close Quarters</option>
				<option value="6">Two Fronts</option>
				<option value="7">Incoming</option>
				<option value="8">Rally Point</option>
				<option value="9">Incursion</option>
				<option value="10">Outflank</option>
				<option value="11">Into the Breach</option>
				<option value="12">Fire Support</option>
				<option value="13">Deathmatch (Hardcore)</option>
				<option value="14">Destruction (Masters)</option>
				<option value="15">Balance of Power (Masters)</option>
				<option value="16">Close Quarters (Masters)</option>
				<option value="17">Incursion (Masters)</option>
				<option value="18">Outflank (Masters)</option>
				<option value="19">Fire Support (Masters)</option>
			</select>
			<a id="ToggleGenerate" onClick="ToggelGenerate()">Roll Random Mission</a>
		</div>
	</div>	
	<div class="row">

		<div class="span8">
			<h4 id="MissionName">Mission Name</h4>
			<h5>Victory Conditions</h5>
			<div id="MissionVictoryConditions">****</div>
			<h5>Special Rules</h5>
			<div id="MissionSpecialRules">****</div>
			<h5>Tactical Tip</h5>
			<div id="MissionTacticalTips">****</div>
		</div>
		<div class="span4">
			<div id="MissionMap">****</div>
		</div>
	</div>
	<div class="row">
		<div class="span4 offset8">
    <div id="MisionObjective">****</div>
	</div>	
</div>
</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "sr20x", root_path, :class => 'brand' %>
<ul class="nav">
    <li><%= link_to 'Mission Index', Mission %></li>
    <li><%= link_to 'Steamroller 2014', page_path('2014/standard') %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "sr20x" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "sr20x.com" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <hr>
            <div class="row">
            <div class="span12 muted">
            <ul class="inline">
                <li><a href="http://privateerpress.com">Privateer Press</a></li>
                <li><%= link_to 'Legal', page_path('legal') %></li>
                <li><a href="http://z1g1.net">z1g1.net</a>
                <li>SR Version 2014 1/21/2014</li>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
            </ul>
            </div>
            </div>
            <div class="row">
                <div class="span12 muted">
                    Contents and Game Rules ©2001–2014 Privateer Press, Inc. All Rights Reserved. Privateer Press®, Iron Kingdoms, WARMACHINE®, Cryx, Convergence of Cyriss, Convergence, Cygnar, Khador, Protectorate of Menoth, Protectorate, Retribution of Scyrah, Retribution, HORDES, Circle Orboros, Circle, Legion of Everblight, Legion, Skorne, Trollbloods, Trollblood, warcaster, warjack, warbeast, Steamroller, Masters, and all associated logos and slogans are trademarks of Privateer Press, Inc. 
                </div>
            </div>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_for @mission do |f| %>
  <% if @mission.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@mission.errors.count, "error") %> prohibited
      this mission from being saved:</h2>
    <ul>
    <% @mission.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
	<div class="row">
		<div class="span2"><%= f.label :name %></div>
		<div class="span10"><%= f.text_field :name %></div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :packet_id %></div>
		<div class="span10">
            <%= f.collection_select(:packet_id, Packet.order(:id),:id,:title, options = {include_blank: true} ) %>		
		</div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :victory, "Victory Conditions" %></div>
		<div class="span10"><%= f.text_area :victory, class: 'field span10'%></div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :specialRules, "Special Rules" %></div>
		<div class="span10"><%= f.text_area :specialRules, class: 'field span10' %></div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :tacticalTips, "Tactical Tips" %></div>
		<div class="span10"><%= f.text_area :tacticalTips, class: 'field span10' %></div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :map %></div>
		<div class="span10"><%= f.text_field :map %></div>
	</div>
	<div class="row">
		<div class="span2"><%= f.label :objective %></div>
		<div class="span10"><%= f.text_field :objective %></div>
	</div>
	<div>
		<div class="span2">
		 <%= f.submit %>
		</div>
	</div>
<% end %>

app/views/missions/edit.html.erb
<h1>New Mission</h1>

<%= render 'form' %>

<div class="row">
	<%= link_to 'Back', missions_path %>
</div>

app/views/missions/index.html.erb
<% content_for :title do %>
Mission Generator
<% end %>

<div class="row">
	<div class="span12">
		Missions >	
	</div>
</div>

<h3>List All Missions </h3>
<% if can? :update, @missions %>
	<div class="row">
		<div class="span12">
			<%= link_to "New Mission",new_mission_path,"class" => "btn btn-success" %>
		</div>
	</div>
<% end %>


<div class="row">
	<div class="span2"><h2>Mission</h2></div>
	<div class="span8"><h2>Special Rules</h2></div>
	<div class="span2"><h2>Map</h2></div>
</div>
<% @missions.each do |mission| %>
<div class="row">
		<div class="span2">
			<h3><%= link_to mission.name,mission_path(mission.id) %></h3>
			<%= mission.packet %> Packet</br>
		  <% if can? :update, mission %>
				<%= link_to 'Edit', edit_mission_path(mission),"class" => "btn btn-primary" %>
				<%= link_to 'Destroy', mission_path(mission), method: :delete, data: { confirm: 'Are you sure?'},"class"=> "btn btn-danger" %>
			<% end %>
		</div>	
		<div class="span8"><%= mission.specialRules.gsub('&lt;','<').gsub('&gt;','>').html_safe %></div>
		<div class="span2"><img class="img-thumbnail" src="http://sr20x.com/static/img/<%= mission.map %>" alt="<%= mission.name %>"></img></div>
</div>
	<% end %>

app/views/missions/new.html.erb
<h1>New Mission</h1>

<%= render 'form' %>

<div class="row">
	<%= link_to 'Back', missions_path %>
</div>

app/views/missions/show.html.erb
<% content_for :title do %>
<%= @mission.name %>
<% end %>

<div class="row">
	<div class="span12">
		<%= link_to 'Missions', Mission %> > <%= link_to Packet.find(@mission.packet_id).title, packet_path(@mission.packet.id) %> >  <%= @mission.name %>
	</div>
</div>

<h3>Mission #<%= @mission.id %> <%= @mission.name %></h3>

<% if can? :update, @mission %>
	<div class="row">
		<div class="span2">
			<%= link_to "Edit Mission",edit_mission_path,"class" => "btn btn-success" %>
		</div>
		<div class="span2">
			<%= link_to 'Destroy', mission_path(@mission), method: :delete, data: { confirm: 'Are you sure?'},"class"=> "btn btn-danger" %>
		</div>
	</div>
<% end %>
<div class="row">

	<div class="span8">
		<h4>Victory</h4>
		<%= @mission.victory.gsub('&lt;','<').gsub('&gt;','>').html_safe %>
		<h4>Special Rules</h4>
		<%= @mission.specialRules.gsub('&lt;','<').gsub('&gt;','>').html_safe %>
		<h4>Tactical Tip</h4>
		<%= @mission.tacticalTips.gsub('&lt;','<').gsub('&gt;','>').html_safe %>
	</div>
	<div class="span4">
		<img src="http://sr20x.com/static/img/<%= @mission.map %>"></img>
	</div>
</div>
<% if @mission.objective? %>
	<div class="row">
		<div class="span4 offset8">
	    <img src="http://sr20x.com/static/img/<%= @mission.objective %>"></img>
		</div>	
	</div>
<% end %>

app/views/packets/index.html.erb
<% content_for :title do %>
Mission Packets 
<% end %>

<% content_for :head do %>
<script type="text/javascript">

</script>
<% end %>

<div class="row">
	<div class="span12">
		Packets >	
	</div>
</div>

<h3>List All Mission Packets </h3>

<div class="row">
	<div class="span12">
        <ul>
        <% @packets.each do |packet| %>
            <li><%= link_to packet.title, packet_path(packet.id) %>
	    <% end %>
        </ul>	
	</div>
</div>

app/views/packets/show.html.erb
<% content_for :title do %>
Missions from <%= @packet.title %>
<% end %>

<div class="row">
	<div class="span12">
		<%= link_to 'Missions', Mission %> > <%= @packet.title %> Packet
	</div>
</div>

<h3>List All Missions in <%= @packet.title %> Packet</h3>

<table class="table table-striped">
<tr>
	<th><h4>Mission</h4></td>
	<th><h4>Special Rules</h4></td>
	<th><h4>Map</h4></td>
</tr>
<% @missions.each do |mission| %>
<tr>
		<td>
		    <h3><%= link_to mission.name,mission_path(mission.id) %></h3>
			<%= link_to Packet.find(mission.packet_id).title, packet_path(mission.packet_id) %></br>
		    <% if can? :update, mission %>
				<%= link_to 'Edit', edit_mission_path(mission),"class" => "btn btn-primary" %>
				<%= link_to 'Destroy', mission_path(mission), method: :delete, data: { confirm: 'Are you sure?'},"class"=> "btn btn-danger" %>
			<% end %>
		</td>	
		<td><%= mission.specialRules.gsub('&lt;','<').gsub('&gt;','>').html_safe %></td>
		<td><div class="span4"><img class="img-thumbnail" src="http://sr20x.com/static/img/<%= mission.map %>" alt="<%= mission.name %>"></img></div></td>
</tr>
	<% end %>
</table>

app/views/pages/2014/_navigation.html.erb
<ul>
    <li><%= link_to 'Steamroller Rules', page_path('2014/standard') %></li>
    <li><%= link_to 'Appendix', page_path('2014/appendix') %></li>
    <li><%= link_to 'Refrence Sheet', page_path('2014/standard-refrence') %></li>
</ul>

app/views/pages/legal.html.erb
<% content_for :title do %>
Legal Information 
<% end %>

<div class="row">
	<div class="span12">
        Legal >
	</div>
</div>

<h3>Legal Information</h3>
<div class="row">
	<div class="span12">
        <h4>For People</h4>
        I created this page as a way to learn Ruby on Rails, mobile web development and because I enjoying playing Warmachine and Hordes. If there is a legal problem please let me know mail at zackglick.com
	</div>
</div>
<div class="row">
	<div class="span12">
        <h4>For Lawyers</h4>
        <p>Contents and Game Rules ©2001-2011 Privateer Press Inc. All Rights Reserved. Privateer Press, WARMACHINE©, Cygnar, Khador, Cryx, Protectorate of Menoth, Retribution of Scyrah, HORDES, Circle Orboros, Legion of Everblight, Skorne, Trollbloods, warcaster, warjack, warbeast, and all associated logos and slogans are trademarks of Privateer Press, Inc. Permission is hereby granted to photocopy and retain electronic copies. Any such duplications shall be intended solely for personal, noncommercial use and must maintain all copyrights, trademarks, or other notices contained therein or preserve all marks associated thereof. Privateer Press reserves the right to remove this permission or revise contents herein at any time for any reason.
        <p>Code for this application is Licensed under the Open Source Initiative OSI - The MIT License
        <p>The MIT License (MIT) Copyright (c) 2011 Zack Glick z1g1.net mail at zackglick.com
        <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
        <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
	</div>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>